root_dir: "/work/nselva2s/rnd"
tfrecord_file: "robile_data_corr_07112024/tfrecords/corr_07112024_withImages_resized_augmented_Critic.tfrecord"
log_dir: "ReinforcementLearning_logs/fit/corr07112024_laser_"
model_name: "critic_laser_corr07112024_a"
model_save_path: "ReinforcementLearning_models"



# Training parameters
train_size: 0.7
val_size: 0.2
batch_size: 128
epochs: 50
train_steps: 2300
val_steps: 600

# Learning rate scheduler parameters
initial_learning_rate: 0.0001
decay_steps: 4500
decay_rate: 0.9
minimum_learning_rate: 0.00005