root_dir: "/work/nselva2s/rnd"
tfrecord_file: "robile_data_corr_07112024/tfrecords/corr_07112024_withImages_resized_augmented.tfrecord"
log_dir: "ImitationLearning_logs/fit/corr07112024_img_laser_aug"
model_name: "model_img_laser_corr07112024_aug_a"
model_save_path: "ImitationLearning_models"


# Training parameters
train_size: 0.7
val_size: 0.2
batch_size: 128
epochs: 500
train_steps: 2300
val_steps: 600

# Learning rate scheduler parameters
initial_learning_rate: 0.005
decay_steps: 10000
decay_rate: 0.96
minimum_learning_rate: 0.0001