input_dir: "/work/nselva2s/rnd/robile_data_corr_07112024"
tfrecord_file: "tfrecords/corr_07112024_withImages_resized_rescaled_outputs.tfrecord"
log_dir: "/work/nselva2s/rnd/logs/fit/corr1_corr_07112024_b"
model_path: "/work/nselva2s/rnd/robile_data_corr1/model_laser_rescaled_outputs_corr1a.keras"
model_save_path: "model_laser_corr1_corr_07112024_b.keras"

# Training parameters
train_size: 0.7
val_size: 0.2
batch_size: 128
epochs: 300
train_steps: 1000
val_steps: 300

# Learning rate scheduler parameters
initial_learning_rate: 0.005
decay_steps: 10000
decay_rate: 0.96
minimum_learning_rate: 0.001